import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'it' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.events': 'Eventi',
    'nav.rooms': 'Camere',
    'nav.services': 'Servizi',
    'nav.spa': 'Spa',
    'nav.church': 'Chiesa',
    'nav.book': 'Prenota',

    // Home Page
    'home.hero.title': 'Benvenuti alla<br />Masseria Termiteto',
    'home.hero.subtitle': 'Un\'autentica dimora storica del XVI secolo immersa tra gli ulivi secolari di Monopoli, dove il lusso incontra la tradizione pugliese',
    'home.hero.cta': 'Scopri il Lusso',
    'home.events.title': 'Eventi da Sogno',
    'home.events.subtitle': 'Matrimoni e celebrazioni indimenticabili nella nostra masseria',
    'home.events.description': 'La nostra masseria offre location uniche per matrimoni esclusivi, con la possibilità di celebrare nella nostra chiesetta consacrata e godere di panorami mozzafiato tra gli ulivi secolari.',
    'home.events.cta': 'Scopri di più',
    'home.rooms.title': 'Camere di Charme',
    'home.rooms.subtitle': 'Trulli autentici e suite di lusso per un soggiorno indimenticabile',
    'home.rooms.description': 'Le nostre eleganti sistemazioni combinano l\'autenticità dei trulli tradizionali con comfort moderni di lusso, offrendo un\'esperienza unica nel cuore della Puglia.',
    'home.rooms.cta': 'Esplora le Camere',
    'home.services.title': 'Servizi Esclusivi',
    'home.services.subtitle': 'Spa, piscine e esperienze culinarie d\'eccellenza',
    'home.services.description': 'Rilassatevi nella nostra spa di lusso, godetevi le nostre piscine panoramiche e delizie culinarie preparate con ingredienti locali d\'eccellenza.',
    'home.services.cta': 'Scopri i Servizi',

    // Events Page
    'events.hero.title': 'Eventi da Sogno',
    'events.hero.subtitle': 'Matrimoni e celebrazioni uniche nella magia della Puglia autentica',
    'events.description1': 'La Masseria Termiteto è la location perfetta per il vostro matrimonio da sogno. I nostri 50 ettari di uliveti secolari offrono scenari mozzafiato per cerimonie indimenticabili.',
    'events.description2': 'La nostra chiesetta consacrata del XVI secolo aggiunge un tocco di sacralità e storia alle vostre nozze, mentre gli spazi esterni permettono ricevimenti eleganti sotto le stelle pugliesi.',
    'events.description3': 'Ogni evento è curato nei minimi dettagli dal nostro team di esperti, che si occuperà di personalizzare ogni aspetto per rendere il vostro giorno davvero speciale.',
    'events.gallery.title': 'Galleria Eventi',
    'events.features.title': 'I Nostri Servizi per Eventi',
    'events.features.church': 'Chiesetta Consacrata',
    'events.features.church.desc': 'Cerimonie religiose nella nostra antica chiesa del XVI secolo',
    'events.features.catering': 'Catering Gourmet',
    'events.features.catering.desc': 'Cucina pugliese d\'eccellenza con ingredienti locali',
    'events.features.gardens': 'Giardini Panoramici',
    'events.features.gardens.desc': 'Spazi esterni suggestivi tra ulivi secolari',
    'events.features.accommodation': 'Sistemazioni Luxury',
    'events.features.accommodation.desc': 'Trulli e suite per ospiti in stile autentico pugliese',

    // Rooms Page
    'rooms.hero.title': 'Camere di Charme',
    'rooms.hero.subtitle': 'Trulli autentici e suite di lusso nel cuore della Puglia',
    'rooms.description1': 'Le nostre eleganti sistemazioni combinano l\'autenticità dell\'architettura pugliese con il comfort moderno di un resort di lusso.',
    'rooms.description2': 'Ogni camera è stata progettata per offrire un\'esperienza unica, con arredi raffinati che rispecchiano la tradizione locale e servizi di altissimo livello.',
    'rooms.description3': 'Godetevi la tranquillità dei nostri giardini privati e la vista mozzafiato sugli uliveti secolari che circondano la masseria.',
    'rooms.trulli.title': 'Trulli Storici',
    'rooms.trulli.desc': 'Autentiche dimore tradizionali restaurate con comfort moderni',
    'rooms.suites.title': 'Suite di Lusso',
    'rooms.suites.desc': 'Ampie suite con vista panoramica e servizi esclusivi',
    'rooms.junior.title': 'Junior Suite',
    'rooms.junior.desc': 'Eleganti spazi con terrazza privata e vista giardino',

    // Services Page
    'services.hero.title': 'Servizi Esclusivi',
    'services.hero.subtitle': 'Una gamma completa di <strong>servizi di lusso</strong> per rendere il vostro soggiorno indimenticabile. Dalla <strong>cucina gourmet</strong> alle aree wellness, ogni dettaglio è curato.',
    'services.intro': 'Una gamma completa di <strong>servizi di lusso</strong> per rendere il vostro soggiorno indimenticabile.<br /><br />Dalla <strong>cucina gourmet</strong> alle aree wellness, ogni dettaglio è curato per offrirvi il massimo comfort in questa <strong>struttura pugliese di lusso</strong>. I nostri servizi uniscono tradizione e innovazione per garantire un\'esperienza unica.',
    'services.list.pool.title': 'Piscine',
    'services.list.pool.desc': 'Piscina esterna riscaldata e piscina coperta con sistema fotovoltaico dedicato',
    'services.list.hot_tub.title': 'Idromassaggio',
    'services.list.hot_tub.desc': 'Area wellness con idromassaggio e zona relax per il vostro benessere',
    'services.list.kitchen.title': 'Cucina Gourmet',
    'services.list.kitchen.desc': 'Cucina industriale professionale per eventi e servizi di ristorazione',
    'services.list.parking.title': 'Parcheggio',
    'services.list.parking.desc': 'Garage coperto da 500 mq e ampi spazi di parcheggio per gli ospiti',
    'services.list.hectares.title': '50 Ettari',
    'services.list.hectares.desc': 'Proprietà immersa in 50 ettari di uliveti e giardini mediterranei',
    'services.list.storage.title': 'Magazzino',
    'services.list.storage.desc': '750 mq di spazi di deposito per eventi e attrezzature',
    'services.list.caretaker.title': 'Casa Custode',
    'services.list.caretaker.desc': 'Servizio di custodia e assistenza 24/7 per la vostra sicurezza',
    'services.list.portico.title': 'Portico Feste',
    'services.list.portico.desc': '235 mq di spazio coperto per eventi e celebrazioni',
    'services.luxury.title': 'Servizi di Lusso',
    'services.luxury.pool.title': 'Piscina Riscaldata All\'Anno',
    'services.luxury.pool.desc': 'Sistema di riscaldamento a energia solare per un comfort ottimale in ogni stagione',
    'services.luxury.kitchen.title': 'Cucina Professionale',
    'services.luxury.kitchen.desc': 'Attrezzature di alta qualità per servizi di catering e ristorazione gourmet',
    'services.luxury.personal.title': 'Servizio Personalizzato',
    'services.luxury.personal.desc': 'Staff dedicato per servizi su misura e assistenza personalizzata',
    'services.gallery.title': 'Galleria Servizi',
    'services.spa.title': 'Centro Benessere',
    'services.spa.desc': 'Spa di lusso con trattamenti rigeneranti e massaggi rilassanti',
    'services.pool.title': 'Piscine Panoramiche',
    'services.pool.desc': 'Piscine infinity con vista mozzafiato sugli uliveti',
    'services.dining.title': 'Ristorante Gourmet',
    'services.dining.desc': 'Cucina pugliese d\'eccellenza con ingredienti locali',
    'services.activities.title': 'Attività Esclusive',
    'services.activities.desc': 'Esperienze enogastronomiche e culturali personalizzate',

    // Spa Page
    'spa.hero.title': 'Spa & Wellness',
    'spa.hero.subtitle': 'Un\'oasi di benessere dove <strong>tradizione pugliese</strong> e <strong>lusso moderno</strong> si fondono.<br /><br />La nostra spa offre trattamenti esclusivi in un ambiente unico.',
    'spa.section.title': 'Spa & Wellness',
    'spa.section.description': 'Un\'oasi di benessere dove <strong>tradizione pugliese</strong> e <strong>lusso moderno</strong> si fondono.<br /><br />La nostra spa offre trattamenti esclusivi in un ambiente unico, tra <strong>piscine riscaldate</strong>, idromassaggio e aree relax immerse nella storia millenaria della masseria. Ogni spazio è progettato per il vostro benessere psicofisico.',
    'spa.features.heading': 'Benessere Autentico',
    'spa.features.covered_pool.title': 'Piscina Coperta Riscaldata',
    'spa.features.covered_pool.description': 'Piscina interna di 220 mq ricavata in un antico fienile, riscaldata tutto l\'anno con sistema fotovoltaico dedicato. Ambiente suggestivo con illuminazione LED cromatica e architettura in pietra tradizionale.',
    'spa.features.hydromassage.title': 'Idromassaggio di Lusso',
    'spa.features.hydromassage.description': 'Area idromassaggio esclusiva con getti terapeutici, perfetta per il relax dopo una giornata di esplorazioni. Ambiente intimo e riservato per momenti di puro benessere.',
    'spa.features.wellness_area.title': 'Area Wellness Ipogea',
    'spa.features.wellness_area.description': 'Nel complesso Trulli Michele, area wellness ricavata in un antico ipogeo sotterraneo. Spazio unico che unisce storia millenaria e tecnologie moderne per il benessere.',
    'spa.services.natural.title': 'Trattamenti Naturali',
    'spa.services.natural.description': 'Massaggi e trattamenti con prodotti tipici pugliesi: olio extravergine, erbe aromatiche e oli essenziali mediterranei',
    'spa.services.hydrotherapy.title': 'Idroterapia',
    'spa.services.hydrotherapy.description': 'Percorsi acquatici terapeutici nelle nostre piscine riscaldate per il benessere del corpo e della mente',
    'spa.services.personalized.title': 'Servizi Personalizzati',
    'spa.services.personalized.description': 'Programmi wellness su misura per soggiorni di relax o preparazione per eventi speciali',
    'spa.gallery.title': 'Galleria Spa',
    'spa.description1': 'Il nostro centro benessere offre un\'esperienza di relax totale, con trattamenti ispirati alle tradizioni pugliesi e tecniche moderne di benessere.',
    'spa.description2': 'Immergetevi in un\'atmosfera di pura tranquillità, dove ogni dettaglio è pensato per il vostro benessere fisico e mentale.',
    'spa.treatments.title': 'I Nostri Trattamenti',
    'spa.massage': 'Massaggi Rilassanti',
    'spa.facial': 'Trattamenti Viso',
    'spa.body': 'Trattamenti Corpo',
    'spa.couples': 'Spa di Coppia',

    // Church Page
    'church.hero.title': 'Chiesa Consacrata',
    'church.hero.subtitle': 'La nostra <strong>chiesa consacrata</strong> del XVII secolo rappresenta il cuore spirituale della masseria. Uno spazio sacro unico per <strong>matrimoni religiosi</strong> e celebrazioni speciali.',
    'church.intro.title': 'Chiesa Consacrata',
    'church.intro.description': 'La nostra <strong>chiesa consacrata</strong> del XVII secolo rappresenta il cuore spirituale della masseria.<br /><br />Completamente restaurata preservando la sua autenticità storica, offre uno spazio sacro unico per <strong>matrimoni religiosi</strong> e celebrazioni speciali in Puglia. Un luogo dove spiritualità e bellezza architettonica si incontrano per creare momenti indimenticabili.',
    'church.history.title': 'Storia e Spiritualità',
    'church.history.paragraph1': 'La <strong>chiesa di Masseria Termiteto</strong> risale al XVII secolo e rappresenta un esempio straordinario di architettura sacra pugliese. Costruita secondo i canoni tradizionali, conserva ancora oggi il suo fascino originario.',
    'church.history.paragraph2': 'Completamente <strong>consacrata e benedetta</strong>, la chiesa è autorizzata per celebrazioni religiose ufficiali, offrendo alle coppie la possibilità di celebrare il loro matrimonio in un contesto di rara bellezza e spiritualità.',
    'church.history.paragraph3': 'L\'<strong>antico campanile</strong> ancora funzionante veglia sulla proprietà, mentre gli interni restaurati con cura mantengono l\'atmosfera sacra e solenne tipica delle chiese pugliesi storiche.',
    'church.features.century.title': 'XVII Secolo',
    'church.features.century.description': 'Costruzione originaria',
    'church.features.size.title': '110 mq',
    'church.features.size.description': 'Superficie totale',
    'church.features.weddings.title': 'Matrimoni Religiosi',
    'church.features.weddings.description': 'Autorizzata per cerimonie',
    'church.features.belltower.title': 'Campanile Storico',
    'church.features.belltower.description': 'Ancora funzionante',
    'church.wedding.title': 'Matrimoni Religiosi',
    'church.wedding.subtitle': 'Celebrate il vostro amore in una cornice di spiritualità autentica e bellezza senza tempo',
    'church.wedding.services.authorized.title': 'Cerimonie Autorizzate',
    'church.wedding.services.authorized.description': 'Matrimoni religiosi ufficiali in ambiente consacrato con validità legale completa',
    'church.wedding.services.music.title': 'Accompagnamento Musicale',
    'church.wedding.services.music.description': 'Servizi di organista e coro per rendere la cerimonia ancora più emozionante',
    'church.wedding.services.photography.title': 'Location Fotografica',
    'church.wedding.services.photography.description': 'Spazi interni ed esterni perfetti per servizi fotografici di matrimonio',
    'church.gallery.title': 'Galleria Chiesa',
    // Booking Page
    'booking.title': 'Prenota il Tuo Soggiorno',
    'booking.subtitle': 'Contattaci per prenotare la tua esperienza di lusso pugliese autentico o per organizzare il tuo evento indimenticabile',
    'booking.form.title': 'Richiedi Informazioni',
    'booking.form.name': 'Nome',
    'booking.form.surname': 'Cognome',
    'booking.form.email': 'Email',
    'booking.form.phone': 'Telefono',
    'booking.form.eventType': 'Tipo di Evento/Soggiorno',
    'booking.form.eventType.placeholder': 'Seleziona...',
    'booking.form.eventType.wedding': 'Matrimonio',
    'booking.form.eventType.event': 'Evento Privato',
    'booking.form.eventType.leisure': 'Soggiorno Leisure',
    'booking.form.eventType.business': 'Meeting/Business',
    'booking.form.expectedDate': 'Data Prevista',
    'booking.form.guests': 'Numero Ospiti',
    'booking.form.message': 'Messaggio',
    'booking.form.message.placeholder': 'Descrivici le tue esigenze...',
    'booking.form.privacy': 'Accetto il trattamento dei dati personali secondo la Privacy Policy',
    'booking.form.submit': 'Invia Richiesta',
    'booking.form.success': 'Richiesta Inviata!',
    'booking.form.success.message': 'Grazie per la tua richiesta! Ti contatteremo presto per discutere le tue esigenze.',
    'booking.form.error': 'Errore',
    'booking.form.error.privacy': 'Devi accettare il trattamento dei dati personali per continuare.',
    'booking.contact.title': 'Contatti Diretti',
    'services.luxury.kitchen.desc': 'High-quality equipment for catering and gourmet dining services',
    'services.luxury.personal.title': 'Personalized Service',
    'services.luxury.personal.desc': 'Dedicated staff for tailor-made services and personalized assistance',
    'services.gallery.title': 'Services Gallery',
    'services.spa.title': 'Wellness Center',
    'services.spa.desc': 'Luxury spa with regenerating treatments and relaxing massages',
    'services.pool.title': 'Panoramic Pools',
    'services.pool.desc': 'Infinity pools with breathtaking views of olive groves',
    'services.dining.title': 'Gourmet Restaurant',
    'services.dining.desc': 'Excellent Apulian cuisine with local ingredients',
    'services.activities.title': 'Exclusive Activities',
    'services.activities.desc': 'Personalized food, wine and cultural experiences',

    // Spa Page
    'spa.hero.title': 'Spa & Wellness',
    'spa.hero.subtitle': 'An oasis of wellness where <strong>Apulian tradition</strong> and <strong>modern luxury</strong> blend.<br /><br />Our spa offers exclusive treatments in a unique environment.',
    'spa.section.title': 'Spa & Wellness',
    'spa.section.description': 'An oasis of wellness where <strong>Apulian tradition</strong> and <strong>modern luxury</strong> come together.<br /><br />Our spa offers exclusive treatments in a unique setting, featuring <strong>heated pools</strong>, hydrotherapy and relaxation areas steeped in the estate\'s millenary history.',
    'spa.features.heading': 'Authentic Wellness',
    'spa.features.covered_pool.title': 'Heated Indoor Pool',
    'spa.features.covered_pool.description': '220 sqm indoor pool created in a former hayloft, heated year-round with a dedicated photovoltaic system. An evocative setting with chromatic LED lighting and traditional stone architecture.',
    'spa.features.hydromassage.title': 'Luxury Hydromassage',
    'spa.features.hydromassage.description': 'Exclusive hydromassage area with therapeutic jets, perfect for relaxing after a day of exploration. An intimate and private environment for moments of pure wellness.',
    'spa.features.wellness_area.title': 'Hypogean Wellness Area',
    'spa.features.wellness_area.description': 'Within the Trulli Michele complex, a wellness area carved out of an ancient underground hypogeum. A unique space that combines centuries-old history with modern wellness technologies.',
    'spa.services.natural.title': 'Natural Treatments',
    'spa.services.natural.description': 'Massages and treatments with typical Apulian products: extra virgin olive oil, aromatic herbs and Mediterranean essential oils',
    'spa.services.hydrotherapy.title': 'Hydrotherapy',
    'spa.services.hydrotherapy.description': 'Therapeutic water pathways in our heated pools for body and mind wellness',
    'spa.services.personalized.title': 'Personalized Services',
    'spa.services.personalized.description': 'Tailor-made wellness programs for relaxing stays or preparation for special events',
    'spa.gallery.title': 'Spa Gallery',
    'spa.description1': 'Our wellness center offers a total relaxation experience, with treatments inspired by Apulian traditions and modern wellness techniques.',
    'spa.description2': 'Immerse yourself in an atmosphere of pure tranquility, where every detail is designed for your physical and mental well-being.',
    'spa.treatments.title': 'Our Treatments',
    'spa.massage': 'Relaxing Massages',
    'spa.facial': 'Facial Treatments',
    'spa.body': 'Body Treatments',
    'spa.couples': 'Couple\'s Spa',

    // Church Page
    'church.hero.title': 'Consecrated Church',
    'church.hero.subtitle': 'Our 17th-century <strong>consecrated church</strong> represents the spiritual heart of the masseria. A sacred space for <strong>religious weddings</strong> and special celebrations.',
    'church.intro.title': 'Consecrated Church',
    'church.intro.description': 'Our 17th-century <strong>consecrated church</strong> represents the spiritual heart of the masseria.<br /><br />Carefully restored while preserving its historic authenticity, it offers a sacred space for <strong>religious weddings</strong> and special celebrations in Puglia. A place where spirituality and architectural beauty meet to create unforgettable moments.',
    'church.history.title': 'History & Spirituality',
    'church.history.paragraph1': '<strong>Masseria Termiteto\'s church</strong> dates back to the 17th century and is an extraordinary example of Apulian sacred architecture. Built according to traditional canons, it still retains its original charm.',
    'church.history.paragraph2': 'Fully <strong>consecrated and blessed</strong>, the church is authorized for official religious celebrations, offering couples the chance to marry in a setting of rare beauty and spirituality.',
    'church.history.paragraph3': 'The <strong>ancient bell tower</strong>, still in operation, watches over the estate while the carefully restored interiors preserve the sacred and solemn atmosphere typical of historic Apulian churches.',
    'church.features.century.title': '17th Century',
    'church.features.century.description': 'Original construction',
    'church.features.size.title': '110 sqm',
    'church.features.size.description': 'Total area',
    'church.features.weddings.title': 'Religious Weddings',
    'church.features.weddings.description': 'Authorized for ceremonies',
    'church.features.belltower.title': 'Historic Bell Tower',
    'church.features.belltower.description': 'Still operational',
    'church.wedding.title': 'Religious Weddings',
    'church.wedding.subtitle': 'Celebrate your love in an authentic spiritual setting with timeless beauty',
    'church.wedding.services.authorized.title': 'Authorized Ceremonies',
    'church.wedding.services.authorized.description': 'Official religious weddings in a consecrated space with full legal validity',
    'church.wedding.services.music.title': 'Musical Accompaniment',
    'church.wedding.services.music.description': 'Organist and choir services to make your ceremony even more moving',
    'church.wedding.services.photography.title': 'Photography Location',
    'church.wedding.services.photography.description': 'Indoor and outdoor spaces perfect for wedding photo shoots',
    'church.gallery.title': 'Church Gallery',
    // Booking Page
    'booking.title': 'Book Your Stay',
    'booking.subtitle': 'Contact us to experience an unforgettable journey',
    'booking.form.name': 'Full Name',
    'booking.form.email': 'Email',
    'booking.form.phone': 'Phone',
    'booking.form.checkin': 'Check-in Date',
    'booking.form.checkout': 'Check-out Date',
    'booking.form.guests': 'Number of Guests',
    'booking.form.message': 'Message',
    'booking.form.submit': 'Send Request',
    'booking.form.success': 'Request sent successfully!',

    // Footer
    'footer.contact': 'Contact',
    'footer.address': 'Contrada Termiteto, 70043 Monopoli BA, Italy',
    'footer.phone': '+39 080 123 4567',
    'footer.email': 'info@masseriaitermiteto.com',
    'footer.follow': 'Follow Us',
    'footer.rights': '© 2024 Masseria Termiteto. All rights reserved.',
    'footer.description': 'Authentic 16th-century Luxury Apulian Resort. Apulian luxury experience among historic trulli, 50 hectares of Mediterranean beauty and millenary tradition.',
    'footer.quicklinks': 'Quick Links',
    'footer.location': 'Our Location',
    'footer.events': 'Events & Weddings',
    'footer.rooms': 'Rooms & Suites',
    'cta.spa': 'Book Your Wellness',
    'cta.events': 'Request Event Quote',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('it');

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}